/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author btssio
 */
public class F_VISITEUR extends javax.swing.JFrame {

    /**
     * Creates new form F_VISITEUR
     */
    public F_VISITEUR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelVisiteur = new javax.swing.JLabel();
        jLabelChercher = new javax.swing.JLabel();
        jComboBoxChercher = new javax.swing.JComboBox();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelAdresse = new javax.swing.JLabel();
        jLabelVille = new javax.swing.JLabel();
        jLabelSecteur = new javax.swing.JLabel();
        jLabelLabo = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldAdresse = new javax.swing.JTextField();
        jTextFieldCodePostal = new javax.swing.JTextField();
        jTextFieldVille = new javax.swing.JTextField();
        jComboBoxSecteur = new javax.swing.JComboBox();
        jComboBoxLabo = new javax.swing.JComboBox();
        jButtonPrecedent1 = new javax.swing.JButton();
        jButtonSuivant1 = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();
        jLabelBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabelVisiteur.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelVisiteur.setText("Visiteur");
        jPanel1.add(jLabelVisiteur);
        jLabelVisiteur.setBounds(310, 10, 137, 23);

        jLabelChercher.setText("Chercher");
        jPanel1.add(jLabelChercher);
        jLabelChercher.setBounds(12, 48, 80, 21);

        jComboBoxChercher.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxChercher);
        jComboBoxChercher.setBounds(130, 48, 101, 21);

        jLabelNom.setText("Nom");
        jPanel1.add(jLabelNom);
        jLabelNom.setBounds(12, 89, 31, 15);

        jLabelPrenom.setText("Prenom");
        jPanel1.add(jLabelPrenom);
        jLabelPrenom.setBounds(12, 120, 54, 15);

        jLabelAdresse.setText("Adresse");
        jPanel1.add(jLabelAdresse);
        jLabelAdresse.setBounds(12, 157, 58, 15);

        jLabelVille.setText("Ville");
        jPanel1.add(jLabelVille);
        jLabelVille.setBounds(12, 194, 30, 15);

        jLabelSecteur.setText("Secteur");
        jPanel1.add(jLabelSecteur);
        jLabelSecteur.setBounds(12, 234, 55, 15);

        jLabelLabo.setText("Labo");
        jPanel1.add(jLabelLabo);
        jLabelLabo.setBounds(12, 276, 35, 15);
        jPanel1.add(jTextFieldNom);
        jTextFieldNom.setBounds(130, 87, 146, 19);
        jPanel1.add(jTextFieldPrenom);
        jTextFieldPrenom.setBounds(130, 118, 146, 19);
        jPanel1.add(jTextFieldAdresse);
        jTextFieldAdresse.setBounds(130, 155, 602, 19);
        jPanel1.add(jTextFieldCodePostal);
        jTextFieldCodePostal.setBounds(130, 192, 39, 19);
        jPanel1.add(jTextFieldVille);
        jTextFieldVille.setBounds(200, 190, 93, 19);

        jComboBoxSecteur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxSecteur);
        jComboBoxSecteur.setBounds(130, 229, 146, 24);

        jComboBoxLabo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxLabo);
        jComboBoxLabo.setBounds(130, 271, 146, 24);

        jButtonPrecedent1.setText("Précédent");
        jPanel1.add(jButtonPrecedent1);
        jButtonPrecedent1.setBounds(190, 320, 107, 25);

        jButtonSuivant1.setText("Suivant");
        jPanel1.add(jButtonSuivant1);
        jButtonSuivant1.setBounds(360, 320, 87, 25);

        jButtonFermer.setText("Fermer");
        jPanel1.add(jButtonFermer);
        jButtonFermer.setBounds(410, 370, 84, 25);

        jLabelBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/GSB.jpg"))); // NOI18N
        jPanel1.add(jLabelBG);
        jLabelBG.setBounds(0, -10, 744, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_VISITEUR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_VISITEUR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_VISITEUR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_VISITEUR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_VISITEUR().setVisible(true);
            }
        });
    }

    public JButton getjButtonFermer() {
        return jButtonFermer;
    }

    public JButton getjButtonPrecedent1() {
        return jButtonPrecedent1;
    }

    public JButton getjButtonSuivant1() {
        return jButtonSuivant1;
    }

    public JComboBox getjComboBoxChercher() {
        return jComboBoxChercher;
    }

    public JComboBox getjComboBoxLabo() {
        return jComboBoxLabo;
    }

    public JComboBox getjComboBoxSecteur() {
        return jComboBoxSecteur;
    }

    public JLabel getjLabelAdresse() {
        return jLabelAdresse;
    }

    public JLabel getjLabelBG() {
        return jLabelBG;
    }

    public JLabel getjLabelChercher() {
        return jLabelChercher;
    }

    public JLabel getjLabelLabo() {
        return jLabelLabo;
    }

    public JLabel getjLabelNom() {
        return jLabelNom;
    }

    public JLabel getjLabelPrenom() {
        return jLabelPrenom;
    }

    public JLabel getjLabelSecteur() {
        return jLabelSecteur;
    }

    public JLabel getjLabelVille() {
        return jLabelVille;
    }

    public JLabel getjLabelVisiteur() {
        return jLabelVisiteur;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JTextField getjTextFieldAdresse() {
        return jTextFieldAdresse;
    }

    public JTextField getjTextFieldCodePostal() {
        return jTextFieldCodePostal;
    }

    public JTextField getjTextFieldNom() {
        return jTextFieldNom;
    }

    public JTextField getjTextFieldPrenom() {
        return jTextFieldPrenom;
    }

    public JTextField getjTextFieldVille() {
        return jTextFieldVille;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonPrecedent1;
    private javax.swing.JButton jButtonSuivant1;
    private javax.swing.JComboBox jComboBoxChercher;
    private javax.swing.JComboBox jComboBoxLabo;
    private javax.swing.JComboBox jComboBoxSecteur;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JLabel jLabelChercher;
    private javax.swing.JLabel jLabelLabo;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelSecteur;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JLabel jLabelVisiteur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldCodePostal;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldVille;
    // End of variables declaration//GEN-END:variables
}
