/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controleur.CtrlMenu;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JToggleButton;


/**
 *
 * @author btssio
 */
public class Menu_General extends javax.swing.JFrame {

    /**
     * Creates new form Menu_General
     */
    public Menu_General() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButtonComptesRendus = new javax.swing.JToggleButton();
        jToggleButtonVisiteurs = new javax.swing.JToggleButton();
        jToggleButtonPraticiens = new javax.swing.JToggleButton();
        jToggleButtonMedicaments = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonDeconnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RAPPORT_VISITE");
        setAlwaysOnTop(true);

        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setLayout(null);

        jToggleButtonComptesRendus.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.disabledForeground"));
        jToggleButtonComptesRendus.setForeground(new java.awt.Color(51, 102, 255));
        jToggleButtonComptesRendus.setText("Rapport de visite");
        jPanel1.add(jToggleButtonComptesRendus);
        jToggleButtonComptesRendus.setBounds(220, 80, 200, 25);

        jToggleButtonVisiteurs.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.disabledForeground"));
        jToggleButtonVisiteurs.setForeground(new java.awt.Color(51, 102, 255));
        jToggleButtonVisiteurs.setText("Visiteurs");
        jPanel1.add(jToggleButtonVisiteurs);
        jToggleButtonVisiteurs.setBounds(220, 140, 200, 25);

        jToggleButtonPraticiens.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.disabledForeground"));
        jToggleButtonPraticiens.setForeground(new java.awt.Color(51, 102, 255));
        jToggleButtonPraticiens.setText("Praticiens");
        jPanel1.add(jToggleButtonPraticiens);
        jToggleButtonPraticiens.setBounds(220, 200, 200, 25);

        jToggleButtonMedicaments.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.disabledForeground"));
        jToggleButtonMedicaments.setForeground(new java.awt.Color(51, 102, 255));
        jToggleButtonMedicaments.setText("Médicaments");
        jPanel1.add(jToggleButtonMedicaments);
        jToggleButtonMedicaments.setBounds(220, 260, 200, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Menu de l'application");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 10, 340, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/logogsb.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 70);

        jButtonDeconnexion.setText("Déconnexion");
        jPanel1.add(jButtonDeconnexion);
        jButtonDeconnexion.setBounds(430, 380, 190, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_General().setVisible(true);
                //new CtrlMenu(this, null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeconnexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButtonComptesRendus;
    private javax.swing.JToggleButton jToggleButtonMedicaments;
    private javax.swing.JToggleButton jToggleButtonPraticiens;
    private javax.swing.JToggleButton jToggleButtonVisiteurs;
    // End of variables declaration//GEN-END:variables



    public JPanel getjPanel1() {
        return jPanel1;
    }
    
    public JButton getjButtonDeconnexion() {
        return jButtonDeconnexion;
    }

    public JToggleButton getjToggleButtonComptesRendus() {
        return jToggleButtonComptesRendus;
    }

    public JToggleButton getjToggleButtonMedicaments() {
        return jToggleButtonMedicaments;
    }

    public JToggleButton getjToggleButtonPraticiens() {
        return jToggleButtonPraticiens;
    }


    public JToggleButton getjToggleButtonVisiteurs() {
        return jToggleButtonVisiteurs;
    }
}
