/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

/**
 *
 * @author btssio
 */
public class RAPPORT_VISITE extends javax.swing.JFrame {

    /**
     * Creates new form RAPPORT_VISITE
     */
    public RAPPORT_VISITE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelNumRapport = new javax.swing.JLabel();
        jTextFieldNumRapport = new javax.swing.JTextField();
        jLabelPraticien = new javax.swing.JLabel();
        jButtonDetails = new javax.swing.JButton();
        jComboBoxPraticien = new javax.swing.JComboBox<String>();
        jLabelDate = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jLabelMotif = new javax.swing.JLabel();
        jTextFieldMotif = new javax.swing.JTextField();
        jLabelBilan = new javax.swing.JLabel();
        jTextFieldBilan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOffre = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonFermer = new javax.swing.JButton();
        jButtonPrecedent = new javax.swing.JButton();
        jButtonSuivant = new javax.swing.JButton();
        jButtonNouveau = new javax.swing.JButton();
        jLabelRapport = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabelNumRapport.setText("Numéro rapport :");
        jPanel1.add(jLabelNumRapport);
        jLabelNumRapport.setBounds(60, 80, 122, 15);
        jPanel1.add(jTextFieldNumRapport);
        jTextFieldNumRapport.setBounds(200, 80, 51, 19);

        jLabelPraticien.setText("Praticien");
        jPanel1.add(jLabelPraticien);
        jLabelPraticien.setBounds(60, 120, 63, 15);

        jButtonDetails.setText("Détails");
        jPanel1.add(jButtonDetails);
        jButtonDetails.setBounds(290, 110, 84, 25);

        jComboBoxPraticien.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxPraticien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxPraticien);
        jComboBoxPraticien.setBounds(200, 110, 83, 24);

        jLabelDate.setText("Date Rapport");
        jPanel1.add(jLabelDate);
        jLabelDate.setBounds(60, 150, 95, 15);
        jPanel1.add(jTextFieldDate);
        jTextFieldDate.setBounds(200, 150, 51, 19);

        jLabelMotif.setText("Motif Visite");
        jPanel1.add(jLabelMotif);
        jLabelMotif.setBounds(60, 190, 80, 15);
        jPanel1.add(jTextFieldMotif);
        jTextFieldMotif.setBounds(200, 190, 83, 19);

        jLabelBilan.setText("BILAN");
        jPanel1.add(jLabelBilan);
        jLabelBilan.setBounds(60, 230, 40, 15);
        jPanel1.add(jTextFieldBilan);
        jTextFieldBilan.setBounds(200, 230, 210, 120);

        jTableOffre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Médicament", "Nb. Echantill."
            }
        ));
        jScrollPane1.setViewportView(jTableOffre);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(450, 230, 288, 90);

        jLabel1.setText("Offre d'échantillons");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 210, 140, 15);

        jButtonFermer.setText("Fermer");
        jPanel1.add(jButtonFermer);
        jButtonFermer.setBounds(480, 420, 84, 25);

        jButtonPrecedent.setText("Précédent");
        jPanel1.add(jButtonPrecedent);
        jButtonPrecedent.setBounds(170, 370, 107, 25);

        jButtonSuivant.setText("Suivant");
        jPanel1.add(jButtonSuivant);
        jButtonSuivant.setBounds(300, 370, 87, 25);

        jButtonNouveau.setText("Nouveau");
        jPanel1.add(jButtonNouveau);
        jButtonNouveau.setBounds(400, 370, 96, 25);

        jLabelRapport.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelRapport.setText("Rapport de Visite");
        jPanel1.add(jLabelRapport);
        jLabelRapport.setBounds(300, 30, 153, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/GSB.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 760, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RAPPORT_VISITE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RAPPORT_VISITE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RAPPORT_VISITE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RAPPORT_VISITE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RAPPORT_VISITE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetails;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonNouveau;
    private javax.swing.JButton jButtonPrecedent;
    private javax.swing.JButton jButtonSuivant;
    private javax.swing.JComboBox<String> jComboBoxPraticien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBilan;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelMotif;
    private javax.swing.JLabel jLabelNumRapport;
    private javax.swing.JLabel jLabelPraticien;
    private javax.swing.JLabel jLabelRapport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTableOffre;
    private javax.swing.JTextField jTextFieldBilan;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldMotif;
    private javax.swing.JTextField jTextFieldNumRapport;
    // End of variables declaration//GEN-END:variables
}
